site_name: Benchmark Docs
theme:
  name: "material"

nav:
  - Klassen:
    - Database: 
      - Methoden: database_methods.md
    - Modelle:
      - Methoden: model_methods.md
    # - Comparison:
    #   - Methoden: compare_methods.md

plugins:
  - search
  - mkdocstrings:
      watch:
        - dev
