site_name: Benchmark Docs
theme:
  name: "material"

nav:
  - Klassen:
    - Database: 
      - Allgemeines: database.md
      - Methoden: database_methods.md

plugins:
  - search
  - mkdocstrings:
      watch:
        - src/dev
